#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siscp.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBsiscp")]
	public partial class siscpDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definições do Método de Extensibilidade
    partial void OnCreated();
    partial void InsertTable_depend(Table_depend instance);
    partial void UpdateTable_depend(Table_depend instance);
    partial void DeleteTable_depend(Table_depend instance);
    partial void InsertTable_titular(Table_titular instance);
    partial void UpdateTable_titular(Table_titular instance);
    partial void DeleteTable_titular(Table_titular instance);
    partial void InsertTable_endereco(Table_endereco instance);
    partial void UpdateTable_endereco(Table_endereco instance);
    partial void DeleteTable_endereco(Table_endereco instance);
    partial void InsertTable_etapa1(Table_etapa1 instance);
    partial void UpdateTable_etapa1(Table_etapa1 instance);
    partial void DeleteTable_etapa1(Table_etapa1 instance);
    partial void InsertTable_etapa2(Table_etapa2 instance);
    partial void UpdateTable_etapa2(Table_etapa2 instance);
    partial void DeleteTable_etapa2(Table_etapa2 instance);
    partial void InsertTable_parentesco(Table_parentesco instance);
    partial void UpdateTable_parentesco(Table_parentesco instance);
    partial void DeleteTable_parentesco(Table_parentesco instance);
    partial void InsertTable_proced(Table_proced instance);
    partial void UpdateTable_proced(Table_proced instance);
    partial void DeleteTable_proced(Table_proced instance);
    partial void InsertTable_status(Table_status instance);
    partial void UpdateTable_status(Table_status instance);
    partial void DeleteTable_status(Table_status instance);
    partial void InsertTable_tratamento1(Table_tratamento1 instance);
    partial void UpdateTable_tratamento1(Table_tratamento1 instance);
    partial void DeleteTable_tratamento1(Table_tratamento1 instance);
    #endregion
		
		public siscpDataContext() : 
				base(global::siscp.DAL.Properties.Settings.Default.DBsiscpConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public siscpDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public siscpDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public siscpDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public siscpDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_depend> Table_depend
		{
			get
			{
				return this.GetTable<Table_depend>();
			}
		}
		
		public System.Data.Linq.Table<Table_titular> Table_titular
		{
			get
			{
				return this.GetTable<Table_titular>();
			}
		}
		
		public System.Data.Linq.Table<Table_endereco> Table_endereco
		{
			get
			{
				return this.GetTable<Table_endereco>();
			}
		}
		
		public System.Data.Linq.Table<Table_etapa1> Table_etapa1
		{
			get
			{
				return this.GetTable<Table_etapa1>();
			}
		}
		
		public System.Data.Linq.Table<Table_etapa2> Table_etapa2
		{
			get
			{
				return this.GetTable<Table_etapa2>();
			}
		}
		
		public System.Data.Linq.Table<Table_parentesco> Table_parentesco
		{
			get
			{
				return this.GetTable<Table_parentesco>();
			}
		}
		
		public System.Data.Linq.Table<Table_proced> Table_proced
		{
			get
			{
				return this.GetTable<Table_proced>();
			}
		}
		
		public System.Data.Linq.Table<Table_status> Table_status
		{
			get
			{
				return this.GetTable<Table_status>();
			}
		}
		
		public System.Data.Linq.Table<Table_tratamento1> Table_tratamento1
		{
			get
			{
				return this.GetTable<Table_tratamento1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_depend")]
	public partial class Table_depend : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_depend;
		
		private System.Nullable<decimal> _cpf_depend;
		
		private string _nome_depend;
		
		private System.Nullable<System.DateTime> _nasc_depend;
		
		private string _end_depend;
		
		private string _bairro_depend;
		
		private System.Nullable<decimal> _cep_depend;
		
		private string _email_depend;
		
		private System.Nullable<int> _id_parentesco_depend;
		
		private string _obs_depend;
		
		private System.Nullable<int> _id_titular_depend;
		
		private System.Nullable<int> _id_endereco_denpend;
		
		private EntitySet<Table_tratamento1> _Table_tratamento1;
		
		private EntityRef<Table_titular> _Table_titular;
		
		private EntityRef<Table_endereco> _Table_endereco;
		
		private EntityRef<Table_parentesco> _Table_parentesco;
		
    #region Definições do Método de Extensibilidade
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dependChanging(int value);
    partial void Onid_dependChanged();
    partial void Oncpf_dependChanging(System.Nullable<decimal> value);
    partial void Oncpf_dependChanged();
    partial void Onnome_dependChanging(string value);
    partial void Onnome_dependChanged();
    partial void Onnasc_dependChanging(System.Nullable<System.DateTime> value);
    partial void Onnasc_dependChanged();
    partial void Onend_dependChanging(string value);
    partial void Onend_dependChanged();
    partial void Onbairro_dependChanging(string value);
    partial void Onbairro_dependChanged();
    partial void Oncep_dependChanging(System.Nullable<decimal> value);
    partial void Oncep_dependChanged();
    partial void Onemail_dependChanging(string value);
    partial void Onemail_dependChanged();
    partial void Onid_parentesco_dependChanging(System.Nullable<int> value);
    partial void Onid_parentesco_dependChanged();
    partial void Onobs_dependChanging(string value);
    partial void Onobs_dependChanged();
    partial void Onid_titular_dependChanging(System.Nullable<int> value);
    partial void Onid_titular_dependChanged();
    partial void Onid_endereco_denpendChanging(System.Nullable<int> value);
    partial void Onid_endereco_denpendChanged();
    #endregion
		
		public Table_depend()
		{
			this._Table_tratamento1 = new EntitySet<Table_tratamento1>(new Action<Table_tratamento1>(this.attach_Table_tratamento1), new Action<Table_tratamento1>(this.detach_Table_tratamento1));
			this._Table_titular = default(EntityRef<Table_titular>);
			this._Table_endereco = default(EntityRef<Table_endereco>);
			this._Table_parentesco = default(EntityRef<Table_parentesco>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_depend", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_depend
		{
			get
			{
				return this._id_depend;
			}
			set
			{
				if ((this._id_depend != value))
				{
					this.Onid_dependChanging(value);
					this.SendPropertyChanging();
					this._id_depend = value;
					this.SendPropertyChanged("id_depend");
					this.Onid_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf_depend", DbType="Decimal(11,0)")]
		public System.Nullable<decimal> cpf_depend
		{
			get
			{
				return this._cpf_depend;
			}
			set
			{
				if ((this._cpf_depend != value))
				{
					this.Oncpf_dependChanging(value);
					this.SendPropertyChanging();
					this._cpf_depend = value;
					this.SendPropertyChanged("cpf_depend");
					this.Oncpf_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_depend", DbType="NChar(30)")]
		public string nome_depend
		{
			get
			{
				return this._nome_depend;
			}
			set
			{
				if ((this._nome_depend != value))
				{
					this.Onnome_dependChanging(value);
					this.SendPropertyChanging();
					this._nome_depend = value;
					this.SendPropertyChanged("nome_depend");
					this.Onnome_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nasc_depend", DbType="Date")]
		public System.Nullable<System.DateTime> nasc_depend
		{
			get
			{
				return this._nasc_depend;
			}
			set
			{
				if ((this._nasc_depend != value))
				{
					this.Onnasc_dependChanging(value);
					this.SendPropertyChanging();
					this._nasc_depend = value;
					this.SendPropertyChanged("nasc_depend");
					this.Onnasc_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_depend", DbType="NChar(30)")]
		public string end_depend
		{
			get
			{
				return this._end_depend;
			}
			set
			{
				if ((this._end_depend != value))
				{
					this.Onend_dependChanging(value);
					this.SendPropertyChanging();
					this._end_depend = value;
					this.SendPropertyChanged("end_depend");
					this.Onend_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro_depend", DbType="NChar(15)")]
		public string bairro_depend
		{
			get
			{
				return this._bairro_depend;
			}
			set
			{
				if ((this._bairro_depend != value))
				{
					this.Onbairro_dependChanging(value);
					this.SendPropertyChanging();
					this._bairro_depend = value;
					this.SendPropertyChanged("bairro_depend");
					this.Onbairro_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep_depend", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> cep_depend
		{
			get
			{
				return this._cep_depend;
			}
			set
			{
				if ((this._cep_depend != value))
				{
					this.Oncep_dependChanging(value);
					this.SendPropertyChanging();
					this._cep_depend = value;
					this.SendPropertyChanged("cep_depend");
					this.Oncep_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_depend", DbType="NChar(30)")]
		public string email_depend
		{
			get
			{
				return this._email_depend;
			}
			set
			{
				if ((this._email_depend != value))
				{
					this.Onemail_dependChanging(value);
					this.SendPropertyChanging();
					this._email_depend = value;
					this.SendPropertyChanged("email_depend");
					this.Onemail_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_parentesco_depend", DbType="Int")]
		public System.Nullable<int> id_parentesco_depend
		{
			get
			{
				return this._id_parentesco_depend;
			}
			set
			{
				if ((this._id_parentesco_depend != value))
				{
					if (this._Table_parentesco.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_parentesco_dependChanging(value);
					this.SendPropertyChanging();
					this._id_parentesco_depend = value;
					this.SendPropertyChanged("id_parentesco_depend");
					this.Onid_parentesco_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obs_depend", DbType="NChar(10)")]
		public string obs_depend
		{
			get
			{
				return this._obs_depend;
			}
			set
			{
				if ((this._obs_depend != value))
				{
					this.Onobs_dependChanging(value);
					this.SendPropertyChanging();
					this._obs_depend = value;
					this.SendPropertyChanged("obs_depend");
					this.Onobs_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_titular_depend", DbType="Int")]
		public System.Nullable<int> id_titular_depend
		{
			get
			{
				return this._id_titular_depend;
			}
			set
			{
				if ((this._id_titular_depend != value))
				{
					if (this._Table_titular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_titular_dependChanging(value);
					this.SendPropertyChanging();
					this._id_titular_depend = value;
					this.SendPropertyChanged("id_titular_depend");
					this.Onid_titular_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_endereco_denpend", DbType="Int")]
		public System.Nullable<int> id_endereco_denpend
		{
			get
			{
				return this._id_endereco_denpend;
			}
			set
			{
				if ((this._id_endereco_denpend != value))
				{
					if (this._Table_endereco.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_endereco_denpendChanging(value);
					this.SendPropertyChanging();
					this._id_endereco_denpend = value;
					this.SendPropertyChanged("id_endereco_denpend");
					this.Onid_endereco_denpendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_depend_Table_tratamento1", Storage="_Table_tratamento1", ThisKey="id_depend", OtherKey="id_depend")]
		public EntitySet<Table_tratamento1> Table_tratamento1
		{
			get
			{
				return this._Table_tratamento1;
			}
			set
			{
				this._Table_tratamento1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_titular_Table_depend", Storage="_Table_titular", ThisKey="id_titular_depend", OtherKey="id_titular", IsForeignKey=true)]
		public Table_titular Table_titular
		{
			get
			{
				return this._Table_titular.Entity;
			}
			set
			{
				Table_titular previousValue = this._Table_titular.Entity;
				if (((previousValue != value) 
							|| (this._Table_titular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_titular.Entity = null;
						previousValue.Table_depend.Remove(this);
					}
					this._Table_titular.Entity = value;
					if ((value != null))
					{
						value.Table_depend.Add(this);
						this._id_titular_depend = value.id_titular;
					}
					else
					{
						this._id_titular_depend = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_titular");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_endereco_Table_depend", Storage="_Table_endereco", ThisKey="id_endereco_denpend", OtherKey="id_endereco", IsForeignKey=true)]
		public Table_endereco Table_endereco
		{
			get
			{
				return this._Table_endereco.Entity;
			}
			set
			{
				Table_endereco previousValue = this._Table_endereco.Entity;
				if (((previousValue != value) 
							|| (this._Table_endereco.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_endereco.Entity = null;
						previousValue.Table_depend.Remove(this);
					}
					this._Table_endereco.Entity = value;
					if ((value != null))
					{
						value.Table_depend.Add(this);
						this._id_endereco_denpend = value.id_endereco;
					}
					else
					{
						this._id_endereco_denpend = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_endereco");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_parentesco_Table_depend", Storage="_Table_parentesco", ThisKey="id_parentesco_depend", OtherKey="id_parentesco", IsForeignKey=true)]
		public Table_parentesco Table_parentesco
		{
			get
			{
				return this._Table_parentesco.Entity;
			}
			set
			{
				Table_parentesco previousValue = this._Table_parentesco.Entity;
				if (((previousValue != value) 
							|| (this._Table_parentesco.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_parentesco.Entity = null;
						previousValue.Table_depend.Remove(this);
					}
					this._Table_parentesco.Entity = value;
					if ((value != null))
					{
						value.Table_depend.Add(this);
						this._id_parentesco_depend = value.id_parentesco;
					}
					else
					{
						this._id_parentesco_depend = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_parentesco");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_tratamento1(Table_tratamento1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_depend = this;
		}
		
		private void detach_Table_tratamento1(Table_tratamento1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_depend = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_titular")]
	public partial class Table_titular : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_titular;
		
		private decimal _cpf_titular;
		
		private string _nome_titular;
		
		private System.DateTime _nasc_titular;
		
		private string _rg_titular;
		
		private string _end_titular;
		
		private System.Nullable<decimal> _cep_titular;
		
		private string _email_titular;
		
		private string _obs_titular;
		
		private string _bairro_titular;
		
		private System.Nullable<int> _id_endereco;
		
		private EntitySet<Table_depend> _Table_depend;
		
		private EntitySet<Table_tratamento1> _Table_tratamento1;
		
		private EntityRef<Table_endereco> _Table_endereco;
		
    #region Definições do Método de Extensibilidade
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_titularChanging(int value);
    partial void Onid_titularChanged();
    partial void Oncpf_titularChanging(decimal value);
    partial void Oncpf_titularChanged();
    partial void Onnome_titularChanging(string value);
    partial void Onnome_titularChanged();
    partial void Onnasc_titularChanging(System.DateTime value);
    partial void Onnasc_titularChanged();
    partial void Onrg_titularChanging(string value);
    partial void Onrg_titularChanged();
    partial void Onend_titularChanging(string value);
    partial void Onend_titularChanged();
    partial void Oncep_titularChanging(System.Nullable<decimal> value);
    partial void Oncep_titularChanged();
    partial void Onemail_titularChanging(string value);
    partial void Onemail_titularChanged();
    partial void Onobs_titularChanging(string value);
    partial void Onobs_titularChanged();
    partial void Onbairro_titularChanging(string value);
    partial void Onbairro_titularChanged();
    partial void Onid_enderecoChanging(System.Nullable<int> value);
    partial void Onid_enderecoChanged();
    #endregion
		
		public Table_titular()
		{
			this._Table_depend = new EntitySet<Table_depend>(new Action<Table_depend>(this.attach_Table_depend), new Action<Table_depend>(this.detach_Table_depend));
			this._Table_tratamento1 = new EntitySet<Table_tratamento1>(new Action<Table_tratamento1>(this.attach_Table_tratamento1), new Action<Table_tratamento1>(this.detach_Table_tratamento1));
			this._Table_endereco = default(EntityRef<Table_endereco>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_titular", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_titular
		{
			get
			{
				return this._id_titular;
			}
			set
			{
				if ((this._id_titular != value))
				{
					this.Onid_titularChanging(value);
					this.SendPropertyChanging();
					this._id_titular = value;
					this.SendPropertyChanged("id_titular");
					this.Onid_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf_titular", DbType="Decimal(11,0) NOT NULL")]
		public decimal cpf_titular
		{
			get
			{
				return this._cpf_titular;
			}
			set
			{
				if ((this._cpf_titular != value))
				{
					this.Oncpf_titularChanging(value);
					this.SendPropertyChanging();
					this._cpf_titular = value;
					this.SendPropertyChanged("cpf_titular");
					this.Oncpf_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_titular", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string nome_titular
		{
			get
			{
				return this._nome_titular;
			}
			set
			{
				if ((this._nome_titular != value))
				{
					this.Onnome_titularChanging(value);
					this.SendPropertyChanging();
					this._nome_titular = value;
					this.SendPropertyChanged("nome_titular");
					this.Onnome_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nasc_titular", DbType="Date NOT NULL")]
		public System.DateTime nasc_titular
		{
			get
			{
				return this._nasc_titular;
			}
			set
			{
				if ((this._nasc_titular != value))
				{
					this.Onnasc_titularChanging(value);
					this.SendPropertyChanging();
					this._nasc_titular = value;
					this.SendPropertyChanged("nasc_titular");
					this.Onnasc_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rg_titular", DbType="NChar(11)")]
		public string rg_titular
		{
			get
			{
				return this._rg_titular;
			}
			set
			{
				if ((this._rg_titular != value))
				{
					this.Onrg_titularChanging(value);
					this.SendPropertyChanging();
					this._rg_titular = value;
					this.SendPropertyChanged("rg_titular");
					this.Onrg_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_titular", DbType="NChar(50)")]
		public string end_titular
		{
			get
			{
				return this._end_titular;
			}
			set
			{
				if ((this._end_titular != value))
				{
					this.Onend_titularChanging(value);
					this.SendPropertyChanging();
					this._end_titular = value;
					this.SendPropertyChanged("end_titular");
					this.Onend_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep_titular", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> cep_titular
		{
			get
			{
				return this._cep_titular;
			}
			set
			{
				if ((this._cep_titular != value))
				{
					this.Oncep_titularChanging(value);
					this.SendPropertyChanging();
					this._cep_titular = value;
					this.SendPropertyChanged("cep_titular");
					this.Oncep_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_titular", DbType="NChar(30)")]
		public string email_titular
		{
			get
			{
				return this._email_titular;
			}
			set
			{
				if ((this._email_titular != value))
				{
					this.Onemail_titularChanging(value);
					this.SendPropertyChanging();
					this._email_titular = value;
					this.SendPropertyChanged("email_titular");
					this.Onemail_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obs_titular", DbType="NChar(50)")]
		public string obs_titular
		{
			get
			{
				return this._obs_titular;
			}
			set
			{
				if ((this._obs_titular != value))
				{
					this.Onobs_titularChanging(value);
					this.SendPropertyChanging();
					this._obs_titular = value;
					this.SendPropertyChanged("obs_titular");
					this.Onobs_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro_titular", DbType="NChar(15)")]
		public string bairro_titular
		{
			get
			{
				return this._bairro_titular;
			}
			set
			{
				if ((this._bairro_titular != value))
				{
					this.Onbairro_titularChanging(value);
					this.SendPropertyChanging();
					this._bairro_titular = value;
					this.SendPropertyChanged("bairro_titular");
					this.Onbairro_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_endereco", DbType="Int")]
		public System.Nullable<int> id_endereco
		{
			get
			{
				return this._id_endereco;
			}
			set
			{
				if ((this._id_endereco != value))
				{
					if (this._Table_endereco.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_enderecoChanging(value);
					this.SendPropertyChanging();
					this._id_endereco = value;
					this.SendPropertyChanged("id_endereco");
					this.Onid_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_titular_Table_depend", Storage="_Table_depend", ThisKey="id_titular", OtherKey="id_titular_depend")]
		public EntitySet<Table_depend> Table_depend
		{
			get
			{
				return this._Table_depend;
			}
			set
			{
				this._Table_depend.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_titular_Table_tratamento1", Storage="_Table_tratamento1", ThisKey="id_titular", OtherKey="id_titular")]
		public EntitySet<Table_tratamento1> Table_tratamento1
		{
			get
			{
				return this._Table_tratamento1;
			}
			set
			{
				this._Table_tratamento1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_endereco_Table_titular", Storage="_Table_endereco", ThisKey="id_endereco", OtherKey="id_endereco", IsForeignKey=true)]
		public Table_endereco Table_endereco
		{
			get
			{
				return this._Table_endereco.Entity;
			}
			set
			{
				Table_endereco previousValue = this._Table_endereco.Entity;
				if (((previousValue != value) 
							|| (this._Table_endereco.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_endereco.Entity = null;
						previousValue.Table_titular.Remove(this);
					}
					this._Table_endereco.Entity = value;
					if ((value != null))
					{
						value.Table_titular.Add(this);
						this._id_endereco = value.id_endereco;
					}
					else
					{
						this._id_endereco = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_endereco");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_depend(Table_depend entity)
		{
			this.SendPropertyChanging();
			entity.Table_titular = this;
		}
		
		private void detach_Table_depend(Table_depend entity)
		{
			this.SendPropertyChanging();
			entity.Table_titular = null;
		}
		
		private void attach_Table_tratamento1(Table_tratamento1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_titular = this;
		}
		
		private void detach_Table_tratamento1(Table_tratamento1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_titular = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_endereco")]
	public partial class Table_endereco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_endereco;
		
		private string _cidades;
		
		private string _estados;
		
		private EntitySet<Table_depend> _Table_depend;
		
		private EntitySet<Table_titular> _Table_titular;
		
    #region Definições do Método de Extensibilidade
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_enderecoChanging(int value);
    partial void Onid_enderecoChanged();
    partial void OncidadesChanging(string value);
    partial void OncidadesChanged();
    partial void OnestadosChanging(string value);
    partial void OnestadosChanged();
    #endregion
		
		public Table_endereco()
		{
			this._Table_depend = new EntitySet<Table_depend>(new Action<Table_depend>(this.attach_Table_depend), new Action<Table_depend>(this.detach_Table_depend));
			this._Table_titular = new EntitySet<Table_titular>(new Action<Table_titular>(this.attach_Table_titular), new Action<Table_titular>(this.detach_Table_titular));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_endereco", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_endereco
		{
			get
			{
				return this._id_endereco;
			}
			set
			{
				if ((this._id_endereco != value))
				{
					this.Onid_enderecoChanging(value);
					this.SendPropertyChanging();
					this._id_endereco = value;
					this.SendPropertyChanged("id_endereco");
					this.Onid_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidades", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cidades
		{
			get
			{
				return this._cidades;
			}
			set
			{
				if ((this._cidades != value))
				{
					this.OncidadesChanging(value);
					this.SendPropertyChanging();
					this._cidades = value;
					this.SendPropertyChanged("cidades");
					this.OncidadesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estados", DbType="NChar(2) NOT NULL", CanBeNull=false)]
		public string estados
		{
			get
			{
				return this._estados;
			}
			set
			{
				if ((this._estados != value))
				{
					this.OnestadosChanging(value);
					this.SendPropertyChanging();
					this._estados = value;
					this.SendPropertyChanged("estados");
					this.OnestadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_endereco_Table_depend", Storage="_Table_depend", ThisKey="id_endereco", OtherKey="id_endereco_denpend")]
		public EntitySet<Table_depend> Table_depend
		{
			get
			{
				return this._Table_depend;
			}
			set
			{
				this._Table_depend.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_endereco_Table_titular", Storage="_Table_titular", ThisKey="id_endereco", OtherKey="id_endereco")]
		public EntitySet<Table_titular> Table_titular
		{
			get
			{
				return this._Table_titular;
			}
			set
			{
				this._Table_titular.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_depend(Table_depend entity)
		{
			this.SendPropertyChanging();
			entity.Table_endereco = this;
		}
		
		private void detach_Table_depend(Table_depend entity)
		{
			this.SendPropertyChanging();
			entity.Table_endereco = null;
		}
		
		private void attach_Table_titular(Table_titular entity)
		{
			this.SendPropertyChanging();
			entity.Table_endereco = this;
		}
		
		private void detach_Table_titular(Table_titular entity)
		{
			this.SendPropertyChanging();
			entity.Table_endereco = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_etapa1")]
	public partial class Table_etapa1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_etapa1;
		
		private System.Nullable<int> _id_proced1;
		
		private string _dente_etapa1;
		
		private System.Nullable<decimal> _valor_paciente1;
		
		private System.Nullable<decimal> _valor_sindicato1;
		
		private System.Nullable<decimal> _valor_pago_paciente1;
		
		private System.Nullable<decimal> _valor_pago_sindicato1;
		
		private System.Nullable<System.DateTime> _data_tratamento1;
		
		private string _unidade_tratamento1;
		
		private EntitySet<Table_tratamento1> _Table_tratamento1;
		
		private EntityRef<Table_proced> _Table_proced;
		
    #region Definições do Método de Extensibilidade
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_etapa1Changing(int value);
    partial void Onid_etapa1Changed();
    partial void Onid_proced1Changing(System.Nullable<int> value);
    partial void Onid_proced1Changed();
    partial void Ondente_etapa1Changing(string value);
    partial void Ondente_etapa1Changed();
    partial void Onvalor_paciente1Changing(System.Nullable<decimal> value);
    partial void Onvalor_paciente1Changed();
    partial void Onvalor_sindicato1Changing(System.Nullable<decimal> value);
    partial void Onvalor_sindicato1Changed();
    partial void Onvalor_pago_paciente1Changing(System.Nullable<decimal> value);
    partial void Onvalor_pago_paciente1Changed();
    partial void Onvalor_pago_sindicato1Changing(System.Nullable<decimal> value);
    partial void Onvalor_pago_sindicato1Changed();
    partial void Ondata_tratamento1Changing(System.Nullable<System.DateTime> value);
    partial void Ondata_tratamento1Changed();
    partial void Onunidade_tratamento1Changing(string value);
    partial void Onunidade_tratamento1Changed();
    #endregion
		
		public Table_etapa1()
		{
			this._Table_tratamento1 = new EntitySet<Table_tratamento1>(new Action<Table_tratamento1>(this.attach_Table_tratamento1), new Action<Table_tratamento1>(this.detach_Table_tratamento1));
			this._Table_proced = default(EntityRef<Table_proced>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_etapa1", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_etapa1
		{
			get
			{
				return this._id_etapa1;
			}
			set
			{
				if ((this._id_etapa1 != value))
				{
					this.Onid_etapa1Changing(value);
					this.SendPropertyChanging();
					this._id_etapa1 = value;
					this.SendPropertyChanged("id_etapa1");
					this.Onid_etapa1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proced1", DbType="Int")]
		public System.Nullable<int> id_proced1
		{
			get
			{
				return this._id_proced1;
			}
			set
			{
				if ((this._id_proced1 != value))
				{
					if (this._Table_proced.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_proced1Changing(value);
					this.SendPropertyChanging();
					this._id_proced1 = value;
					this.SendPropertyChanged("id_proced1");
					this.Onid_proced1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dente_etapa1", DbType="NChar(20)")]
		public string dente_etapa1
		{
			get
			{
				return this._dente_etapa1;
			}
			set
			{
				if ((this._dente_etapa1 != value))
				{
					this.Ondente_etapa1Changing(value);
					this.SendPropertyChanging();
					this._dente_etapa1 = value;
					this.SendPropertyChanged("dente_etapa1");
					this.Ondente_etapa1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_paciente1", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valor_paciente1
		{
			get
			{
				return this._valor_paciente1;
			}
			set
			{
				if ((this._valor_paciente1 != value))
				{
					this.Onvalor_paciente1Changing(value);
					this.SendPropertyChanging();
					this._valor_paciente1 = value;
					this.SendPropertyChanged("valor_paciente1");
					this.Onvalor_paciente1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_sindicato1", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valor_sindicato1
		{
			get
			{
				return this._valor_sindicato1;
			}
			set
			{
				if ((this._valor_sindicato1 != value))
				{
					this.Onvalor_sindicato1Changing(value);
					this.SendPropertyChanging();
					this._valor_sindicato1 = value;
					this.SendPropertyChanged("valor_sindicato1");
					this.Onvalor_sindicato1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_pago_paciente1", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valor_pago_paciente1
		{
			get
			{
				return this._valor_pago_paciente1;
			}
			set
			{
				if ((this._valor_pago_paciente1 != value))
				{
					this.Onvalor_pago_paciente1Changing(value);
					this.SendPropertyChanging();
					this._valor_pago_paciente1 = value;
					this.SendPropertyChanged("valor_pago_paciente1");
					this.Onvalor_pago_paciente1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_pago_sindicato1", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valor_pago_sindicato1
		{
			get
			{
				return this._valor_pago_sindicato1;
			}
			set
			{
				if ((this._valor_pago_sindicato1 != value))
				{
					this.Onvalor_pago_sindicato1Changing(value);
					this.SendPropertyChanging();
					this._valor_pago_sindicato1 = value;
					this.SendPropertyChanged("valor_pago_sindicato1");
					this.Onvalor_pago_sindicato1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_tratamento1", DbType="Date")]
		public System.Nullable<System.DateTime> data_tratamento1
		{
			get
			{
				return this._data_tratamento1;
			}
			set
			{
				if ((this._data_tratamento1 != value))
				{
					this.Ondata_tratamento1Changing(value);
					this.SendPropertyChanging();
					this._data_tratamento1 = value;
					this.SendPropertyChanged("data_tratamento1");
					this.Ondata_tratamento1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidade_tratamento1", DbType="NChar(15)")]
		public string unidade_tratamento1
		{
			get
			{
				return this._unidade_tratamento1;
			}
			set
			{
				if ((this._unidade_tratamento1 != value))
				{
					this.Onunidade_tratamento1Changing(value);
					this.SendPropertyChanging();
					this._unidade_tratamento1 = value;
					this.SendPropertyChanged("unidade_tratamento1");
					this.Onunidade_tratamento1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_etapa1_Table_tratamento1", Storage="_Table_tratamento1", ThisKey="id_etapa1", OtherKey="id_etapa1")]
		public EntitySet<Table_tratamento1> Table_tratamento1
		{
			get
			{
				return this._Table_tratamento1;
			}
			set
			{
				this._Table_tratamento1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_proced_Table_etapa1", Storage="_Table_proced", ThisKey="id_proced1", OtherKey="id_proced", IsForeignKey=true)]
		public Table_proced Table_proced
		{
			get
			{
				return this._Table_proced.Entity;
			}
			set
			{
				Table_proced previousValue = this._Table_proced.Entity;
				if (((previousValue != value) 
							|| (this._Table_proced.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_proced.Entity = null;
						previousValue.Table_etapa1.Remove(this);
					}
					this._Table_proced.Entity = value;
					if ((value != null))
					{
						value.Table_etapa1.Add(this);
						this._id_proced1 = value.id_proced;
					}
					else
					{
						this._id_proced1 = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_proced");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_tratamento1(Table_tratamento1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_etapa1 = this;
		}
		
		private void detach_Table_tratamento1(Table_tratamento1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_etapa1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_etapa2")]
	public partial class Table_etapa2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_etapa2;
		
		private System.Nullable<int> _id_proced2;
		
		private string _dente_etapa2;
		
		private System.Nullable<decimal> _valor_paciente2;
		
		private System.Nullable<decimal> _valor_sindicato2;
		
		private System.Nullable<decimal> _valor_pago_paciente2;
		
		private System.Nullable<decimal> _valor_pago_sindicato2;
		
		private System.Nullable<System.DateTime> _data_tratamento2;
		
		private string _unidade_tratamento2;
		
		private EntitySet<Table_tratamento1> _Table_tratamento1;
		
		private EntityRef<Table_proced> _Table_proced;
		
    #region Definições do Método de Extensibilidade
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_etapa2Changing(int value);
    partial void Onid_etapa2Changed();
    partial void Onid_proced2Changing(System.Nullable<int> value);
    partial void Onid_proced2Changed();
    partial void Ondente_etapa2Changing(string value);
    partial void Ondente_etapa2Changed();
    partial void Onvalor_paciente2Changing(System.Nullable<decimal> value);
    partial void Onvalor_paciente2Changed();
    partial void Onvalor_sindicato2Changing(System.Nullable<decimal> value);
    partial void Onvalor_sindicato2Changed();
    partial void Onvalor_pago_paciente2Changing(System.Nullable<decimal> value);
    partial void Onvalor_pago_paciente2Changed();
    partial void Onvalor_pago_sindicato2Changing(System.Nullable<decimal> value);
    partial void Onvalor_pago_sindicato2Changed();
    partial void Ondata_tratamento2Changing(System.Nullable<System.DateTime> value);
    partial void Ondata_tratamento2Changed();
    partial void Onunidade_tratamento2Changing(string value);
    partial void Onunidade_tratamento2Changed();
    #endregion
		
		public Table_etapa2()
		{
			this._Table_tratamento1 = new EntitySet<Table_tratamento1>(new Action<Table_tratamento1>(this.attach_Table_tratamento1), new Action<Table_tratamento1>(this.detach_Table_tratamento1));
			this._Table_proced = default(EntityRef<Table_proced>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_etapa2", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_etapa2
		{
			get
			{
				return this._id_etapa2;
			}
			set
			{
				if ((this._id_etapa2 != value))
				{
					this.Onid_etapa2Changing(value);
					this.SendPropertyChanging();
					this._id_etapa2 = value;
					this.SendPropertyChanged("id_etapa2");
					this.Onid_etapa2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proced2", DbType="Int")]
		public System.Nullable<int> id_proced2
		{
			get
			{
				return this._id_proced2;
			}
			set
			{
				if ((this._id_proced2 != value))
				{
					if (this._Table_proced.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_proced2Changing(value);
					this.SendPropertyChanging();
					this._id_proced2 = value;
					this.SendPropertyChanged("id_proced2");
					this.Onid_proced2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dente_etapa2", DbType="NChar(20)")]
		public string dente_etapa2
		{
			get
			{
				return this._dente_etapa2;
			}
			set
			{
				if ((this._dente_etapa2 != value))
				{
					this.Ondente_etapa2Changing(value);
					this.SendPropertyChanging();
					this._dente_etapa2 = value;
					this.SendPropertyChanged("dente_etapa2");
					this.Ondente_etapa2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_paciente2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valor_paciente2
		{
			get
			{
				return this._valor_paciente2;
			}
			set
			{
				if ((this._valor_paciente2 != value))
				{
					this.Onvalor_paciente2Changing(value);
					this.SendPropertyChanging();
					this._valor_paciente2 = value;
					this.SendPropertyChanged("valor_paciente2");
					this.Onvalor_paciente2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_sindicato2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valor_sindicato2
		{
			get
			{
				return this._valor_sindicato2;
			}
			set
			{
				if ((this._valor_sindicato2 != value))
				{
					this.Onvalor_sindicato2Changing(value);
					this.SendPropertyChanging();
					this._valor_sindicato2 = value;
					this.SendPropertyChanged("valor_sindicato2");
					this.Onvalor_sindicato2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_pago_paciente2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valor_pago_paciente2
		{
			get
			{
				return this._valor_pago_paciente2;
			}
			set
			{
				if ((this._valor_pago_paciente2 != value))
				{
					this.Onvalor_pago_paciente2Changing(value);
					this.SendPropertyChanging();
					this._valor_pago_paciente2 = value;
					this.SendPropertyChanged("valor_pago_paciente2");
					this.Onvalor_pago_paciente2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_pago_sindicato2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valor_pago_sindicato2
		{
			get
			{
				return this._valor_pago_sindicato2;
			}
			set
			{
				if ((this._valor_pago_sindicato2 != value))
				{
					this.Onvalor_pago_sindicato2Changing(value);
					this.SendPropertyChanging();
					this._valor_pago_sindicato2 = value;
					this.SendPropertyChanged("valor_pago_sindicato2");
					this.Onvalor_pago_sindicato2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_tratamento2", DbType="Date")]
		public System.Nullable<System.DateTime> data_tratamento2
		{
			get
			{
				return this._data_tratamento2;
			}
			set
			{
				if ((this._data_tratamento2 != value))
				{
					this.Ondata_tratamento2Changing(value);
					this.SendPropertyChanging();
					this._data_tratamento2 = value;
					this.SendPropertyChanged("data_tratamento2");
					this.Ondata_tratamento2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidade_tratamento2", DbType="NChar(15)")]
		public string unidade_tratamento2
		{
			get
			{
				return this._unidade_tratamento2;
			}
			set
			{
				if ((this._unidade_tratamento2 != value))
				{
					this.Onunidade_tratamento2Changing(value);
					this.SendPropertyChanging();
					this._unidade_tratamento2 = value;
					this.SendPropertyChanged("unidade_tratamento2");
					this.Onunidade_tratamento2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_etapa2_Table_tratamento1", Storage="_Table_tratamento1", ThisKey="id_etapa2", OtherKey="id_etapa2")]
		public EntitySet<Table_tratamento1> Table_tratamento1
		{
			get
			{
				return this._Table_tratamento1;
			}
			set
			{
				this._Table_tratamento1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_proced_Table_etapa2", Storage="_Table_proced", ThisKey="id_proced2", OtherKey="id_proced", IsForeignKey=true)]
		public Table_proced Table_proced
		{
			get
			{
				return this._Table_proced.Entity;
			}
			set
			{
				Table_proced previousValue = this._Table_proced.Entity;
				if (((previousValue != value) 
							|| (this._Table_proced.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_proced.Entity = null;
						previousValue.Table_etapa2.Remove(this);
					}
					this._Table_proced.Entity = value;
					if ((value != null))
					{
						value.Table_etapa2.Add(this);
						this._id_proced2 = value.id_proced;
					}
					else
					{
						this._id_proced2 = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_proced");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_tratamento1(Table_tratamento1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_etapa2 = this;
		}
		
		private void detach_Table_tratamento1(Table_tratamento1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_etapa2 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_parentesco")]
	public partial class Table_parentesco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_parentesco;
		
		private string _desc_parentesco;
		
		private EntitySet<Table_depend> _Table_depend;
		
    #region Definições do Método de Extensibilidade
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_parentescoChanging(int value);
    partial void Onid_parentescoChanged();
    partial void Ondesc_parentescoChanging(string value);
    partial void Ondesc_parentescoChanged();
    #endregion
		
		public Table_parentesco()
		{
			this._Table_depend = new EntitySet<Table_depend>(new Action<Table_depend>(this.attach_Table_depend), new Action<Table_depend>(this.detach_Table_depend));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_parentesco", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_parentesco
		{
			get
			{
				return this._id_parentesco;
			}
			set
			{
				if ((this._id_parentesco != value))
				{
					this.Onid_parentescoChanging(value);
					this.SendPropertyChanging();
					this._id_parentesco = value;
					this.SendPropertyChanged("id_parentesco");
					this.Onid_parentescoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_parentesco", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string desc_parentesco
		{
			get
			{
				return this._desc_parentesco;
			}
			set
			{
				if ((this._desc_parentesco != value))
				{
					this.Ondesc_parentescoChanging(value);
					this.SendPropertyChanging();
					this._desc_parentesco = value;
					this.SendPropertyChanged("desc_parentesco");
					this.Ondesc_parentescoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_parentesco_Table_depend", Storage="_Table_depend", ThisKey="id_parentesco", OtherKey="id_parentesco_depend")]
		public EntitySet<Table_depend> Table_depend
		{
			get
			{
				return this._Table_depend;
			}
			set
			{
				this._Table_depend.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_depend(Table_depend entity)
		{
			this.SendPropertyChanging();
			entity.Table_parentesco = this;
		}
		
		private void detach_Table_depend(Table_depend entity)
		{
			this.SendPropertyChanging();
			entity.Table_parentesco = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_proced")]
	public partial class Table_proced : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_proced;
		
		private string _desc_proced;
		
		private System.Nullable<decimal> _valor_proced;
		
		private EntitySet<Table_etapa1> _Table_etapa1;
		
		private EntitySet<Table_etapa2> _Table_etapa2;
		
    #region Definições do Método de Extensibilidade
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_procedChanging(int value);
    partial void Onid_procedChanged();
    partial void Ondesc_procedChanging(string value);
    partial void Ondesc_procedChanged();
    partial void Onvalor_procedChanging(System.Nullable<decimal> value);
    partial void Onvalor_procedChanged();
    #endregion
		
		public Table_proced()
		{
			this._Table_etapa1 = new EntitySet<Table_etapa1>(new Action<Table_etapa1>(this.attach_Table_etapa1), new Action<Table_etapa1>(this.detach_Table_etapa1));
			this._Table_etapa2 = new EntitySet<Table_etapa2>(new Action<Table_etapa2>(this.attach_Table_etapa2), new Action<Table_etapa2>(this.detach_Table_etapa2));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proced", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_proced
		{
			get
			{
				return this._id_proced;
			}
			set
			{
				if ((this._id_proced != value))
				{
					this.Onid_procedChanging(value);
					this.SendPropertyChanging();
					this._id_proced = value;
					this.SendPropertyChanged("id_proced");
					this.Onid_procedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_proced", DbType="NChar(50)")]
		public string desc_proced
		{
			get
			{
				return this._desc_proced;
			}
			set
			{
				if ((this._desc_proced != value))
				{
					this.Ondesc_procedChanging(value);
					this.SendPropertyChanging();
					this._desc_proced = value;
					this.SendPropertyChanged("desc_proced");
					this.Ondesc_procedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_proced", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valor_proced
		{
			get
			{
				return this._valor_proced;
			}
			set
			{
				if ((this._valor_proced != value))
				{
					this.Onvalor_procedChanging(value);
					this.SendPropertyChanging();
					this._valor_proced = value;
					this.SendPropertyChanged("valor_proced");
					this.Onvalor_procedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_proced_Table_etapa1", Storage="_Table_etapa1", ThisKey="id_proced", OtherKey="id_proced1")]
		public EntitySet<Table_etapa1> Table_etapa1
		{
			get
			{
				return this._Table_etapa1;
			}
			set
			{
				this._Table_etapa1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_proced_Table_etapa2", Storage="_Table_etapa2", ThisKey="id_proced", OtherKey="id_proced2")]
		public EntitySet<Table_etapa2> Table_etapa2
		{
			get
			{
				return this._Table_etapa2;
			}
			set
			{
				this._Table_etapa2.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_etapa1(Table_etapa1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_proced = this;
		}
		
		private void detach_Table_etapa1(Table_etapa1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_proced = null;
		}
		
		private void attach_Table_etapa2(Table_etapa2 entity)
		{
			this.SendPropertyChanging();
			entity.Table_proced = this;
		}
		
		private void detach_Table_etapa2(Table_etapa2 entity)
		{
			this.SendPropertyChanging();
			entity.Table_proced = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_status")]
	public partial class Table_status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _desc_status;
		
		private EntitySet<Table_tratamento1> _Table_tratamento1;
		
    #region Definições do Método de Extensibilidade
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void Ondesc_statusChanging(string value);
    partial void Ondesc_statusChanged();
    #endregion
		
		public Table_status()
		{
			this._Table_tratamento1 = new EntitySet<Table_tratamento1>(new Action<Table_tratamento1>(this.attach_Table_tratamento1), new Action<Table_tratamento1>(this.detach_Table_tratamento1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_status", DbType="NChar(20)")]
		public string desc_status
		{
			get
			{
				return this._desc_status;
			}
			set
			{
				if ((this._desc_status != value))
				{
					this.Ondesc_statusChanging(value);
					this.SendPropertyChanging();
					this._desc_status = value;
					this.SendPropertyChanged("desc_status");
					this.Ondesc_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_status_Table_tratamento1", Storage="_Table_tratamento1", ThisKey="id_status", OtherKey="id_status")]
		public EntitySet<Table_tratamento1> Table_tratamento1
		{
			get
			{
				return this._Table_tratamento1;
			}
			set
			{
				this._Table_tratamento1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_tratamento1(Table_tratamento1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_status = this;
		}
		
		private void detach_Table_tratamento1(Table_tratamento1 entity)
		{
			this.SendPropertyChanging();
			entity.Table_status = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_tratamento1")]
	public partial class Table_tratamento1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tratamento;
		
		private System.Nullable<int> _id_titular;
		
		private System.Nullable<int> _id_depend;
		
		private System.Nullable<int> _id_endereco;
		
		private System.Nullable<int> _id_telefone;
		
		private System.Nullable<int> _id_status;
		
		private System.Nullable<int> _id_etapa1;
		
		private string _nf_tratamento1;
		
		private System.Nullable<System.DateTime> _data_pagamento_tratamento1;
		
		private System.Nullable<int> _id_etapa2;
		
		private EntityRef<Table_depend> _Table_depend;
		
		private EntityRef<Table_etapa1> _Table_etapa1;
		
		private EntityRef<Table_etapa2> _Table_etapa2;
		
		private EntityRef<Table_status> _Table_status;
		
		private EntityRef<Table_titular> _Table_titular;
		
    #region Definições do Método de Extensibilidade
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tratamentoChanging(int value);
    partial void Onid_tratamentoChanged();
    partial void Onid_titularChanging(System.Nullable<int> value);
    partial void Onid_titularChanged();
    partial void Onid_dependChanging(System.Nullable<int> value);
    partial void Onid_dependChanged();
    partial void Onid_enderecoChanging(System.Nullable<int> value);
    partial void Onid_enderecoChanged();
    partial void Onid_telefoneChanging(System.Nullable<int> value);
    partial void Onid_telefoneChanged();
    partial void Onid_statusChanging(System.Nullable<int> value);
    partial void Onid_statusChanged();
    partial void Onid_etapa1Changing(System.Nullable<int> value);
    partial void Onid_etapa1Changed();
    partial void Onnf_tratamento1Changing(string value);
    partial void Onnf_tratamento1Changed();
    partial void Ondata_pagamento_tratamento1Changing(System.Nullable<System.DateTime> value);
    partial void Ondata_pagamento_tratamento1Changed();
    partial void Onid_etapa2Changing(System.Nullable<int> value);
    partial void Onid_etapa2Changed();
    #endregion
		
		public Table_tratamento1()
		{
			this._Table_depend = default(EntityRef<Table_depend>);
			this._Table_etapa1 = default(EntityRef<Table_etapa1>);
			this._Table_etapa2 = default(EntityRef<Table_etapa2>);
			this._Table_status = default(EntityRef<Table_status>);
			this._Table_titular = default(EntityRef<Table_titular>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tratamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tratamento
		{
			get
			{
				return this._id_tratamento;
			}
			set
			{
				if ((this._id_tratamento != value))
				{
					this.Onid_tratamentoChanging(value);
					this.SendPropertyChanging();
					this._id_tratamento = value;
					this.SendPropertyChanged("id_tratamento");
					this.Onid_tratamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_titular", DbType="Int")]
		public System.Nullable<int> id_titular
		{
			get
			{
				return this._id_titular;
			}
			set
			{
				if ((this._id_titular != value))
				{
					if (this._Table_titular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_titularChanging(value);
					this.SendPropertyChanging();
					this._id_titular = value;
					this.SendPropertyChanged("id_titular");
					this.Onid_titularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_depend", DbType="Int")]
		public System.Nullable<int> id_depend
		{
			get
			{
				return this._id_depend;
			}
			set
			{
				if ((this._id_depend != value))
				{
					if (this._Table_depend.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_dependChanging(value);
					this.SendPropertyChanging();
					this._id_depend = value;
					this.SendPropertyChanged("id_depend");
					this.Onid_dependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_endereco", DbType="Int")]
		public System.Nullable<int> id_endereco
		{
			get
			{
				return this._id_endereco;
			}
			set
			{
				if ((this._id_endereco != value))
				{
					this.Onid_enderecoChanging(value);
					this.SendPropertyChanging();
					this._id_endereco = value;
					this.SendPropertyChanged("id_endereco");
					this.Onid_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_telefone", DbType="Int")]
		public System.Nullable<int> id_telefone
		{
			get
			{
				return this._id_telefone;
			}
			set
			{
				if ((this._id_telefone != value))
				{
					this.Onid_telefoneChanging(value);
					this.SendPropertyChanging();
					this._id_telefone = value;
					this.SendPropertyChanged("id_telefone");
					this.Onid_telefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int")]
		public System.Nullable<int> id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					if (this._Table_status.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_etapa1", DbType="Int")]
		public System.Nullable<int> id_etapa1
		{
			get
			{
				return this._id_etapa1;
			}
			set
			{
				if ((this._id_etapa1 != value))
				{
					if (this._Table_etapa1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_etapa1Changing(value);
					this.SendPropertyChanging();
					this._id_etapa1 = value;
					this.SendPropertyChanged("id_etapa1");
					this.Onid_etapa1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nf_tratamento1", DbType="NChar(30)")]
		public string nf_tratamento1
		{
			get
			{
				return this._nf_tratamento1;
			}
			set
			{
				if ((this._nf_tratamento1 != value))
				{
					this.Onnf_tratamento1Changing(value);
					this.SendPropertyChanging();
					this._nf_tratamento1 = value;
					this.SendPropertyChanged("nf_tratamento1");
					this.Onnf_tratamento1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_pagamento_tratamento1", DbType="Date")]
		public System.Nullable<System.DateTime> data_pagamento_tratamento1
		{
			get
			{
				return this._data_pagamento_tratamento1;
			}
			set
			{
				if ((this._data_pagamento_tratamento1 != value))
				{
					this.Ondata_pagamento_tratamento1Changing(value);
					this.SendPropertyChanging();
					this._data_pagamento_tratamento1 = value;
					this.SendPropertyChanged("data_pagamento_tratamento1");
					this.Ondata_pagamento_tratamento1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_etapa2", DbType="Int")]
		public System.Nullable<int> id_etapa2
		{
			get
			{
				return this._id_etapa2;
			}
			set
			{
				if ((this._id_etapa2 != value))
				{
					if (this._Table_etapa2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_etapa2Changing(value);
					this.SendPropertyChanging();
					this._id_etapa2 = value;
					this.SendPropertyChanged("id_etapa2");
					this.Onid_etapa2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_depend_Table_tratamento1", Storage="_Table_depend", ThisKey="id_depend", OtherKey="id_depend", IsForeignKey=true)]
		public Table_depend Table_depend
		{
			get
			{
				return this._Table_depend.Entity;
			}
			set
			{
				Table_depend previousValue = this._Table_depend.Entity;
				if (((previousValue != value) 
							|| (this._Table_depend.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_depend.Entity = null;
						previousValue.Table_tratamento1.Remove(this);
					}
					this._Table_depend.Entity = value;
					if ((value != null))
					{
						value.Table_tratamento1.Add(this);
						this._id_depend = value.id_depend;
					}
					else
					{
						this._id_depend = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_depend");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_etapa1_Table_tratamento1", Storage="_Table_etapa1", ThisKey="id_etapa1", OtherKey="id_etapa1", IsForeignKey=true)]
		public Table_etapa1 Table_etapa1
		{
			get
			{
				return this._Table_etapa1.Entity;
			}
			set
			{
				Table_etapa1 previousValue = this._Table_etapa1.Entity;
				if (((previousValue != value) 
							|| (this._Table_etapa1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_etapa1.Entity = null;
						previousValue.Table_tratamento1.Remove(this);
					}
					this._Table_etapa1.Entity = value;
					if ((value != null))
					{
						value.Table_tratamento1.Add(this);
						this._id_etapa1 = value.id_etapa1;
					}
					else
					{
						this._id_etapa1 = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_etapa1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_etapa2_Table_tratamento1", Storage="_Table_etapa2", ThisKey="id_etapa2", OtherKey="id_etapa2", IsForeignKey=true)]
		public Table_etapa2 Table_etapa2
		{
			get
			{
				return this._Table_etapa2.Entity;
			}
			set
			{
				Table_etapa2 previousValue = this._Table_etapa2.Entity;
				if (((previousValue != value) 
							|| (this._Table_etapa2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_etapa2.Entity = null;
						previousValue.Table_tratamento1.Remove(this);
					}
					this._Table_etapa2.Entity = value;
					if ((value != null))
					{
						value.Table_tratamento1.Add(this);
						this._id_etapa2 = value.id_etapa2;
					}
					else
					{
						this._id_etapa2 = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_etapa2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_status_Table_tratamento1", Storage="_Table_status", ThisKey="id_status", OtherKey="id_status", IsForeignKey=true)]
		public Table_status Table_status
		{
			get
			{
				return this._Table_status.Entity;
			}
			set
			{
				Table_status previousValue = this._Table_status.Entity;
				if (((previousValue != value) 
							|| (this._Table_status.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_status.Entity = null;
						previousValue.Table_tratamento1.Remove(this);
					}
					this._Table_status.Entity = value;
					if ((value != null))
					{
						value.Table_tratamento1.Add(this);
						this._id_status = value.id_status;
					}
					else
					{
						this._id_status = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_status");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_titular_Table_tratamento1", Storage="_Table_titular", ThisKey="id_titular", OtherKey="id_titular", IsForeignKey=true)]
		public Table_titular Table_titular
		{
			get
			{
				return this._Table_titular.Entity;
			}
			set
			{
				Table_titular previousValue = this._Table_titular.Entity;
				if (((previousValue != value) 
							|| (this._Table_titular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_titular.Entity = null;
						previousValue.Table_tratamento1.Remove(this);
					}
					this._Table_titular.Entity = value;
					if ((value != null))
					{
						value.Table_tratamento1.Add(this);
						this._id_titular = value.id_titular;
					}
					else
					{
						this._id_titular = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_titular");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
